-- MySQL Script generated by MySQL Workbench
-- qui 23 abr 2020 20:13:07 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bring2medb
-- -----------------------------------------------------
-- Banco de dados da Aplicação Bring2Me.
DROP SCHEMA IF EXISTS `bring2medb` ;

-- -----------------------------------------------------
-- Schema bring2medb
--
-- Banco de dados da Aplicação Bring2Me.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bring2medb` DEFAULT CHARACTER SET utf8 ;
USE `bring2medb` ;

-- -----------------------------------------------------
-- Table `bring2medb`.`tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bring2medb`.`tb_usuario` ;

CREATE TABLE IF NOT EXISTS `bring2medb`.`tb_usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf_cnpj` VARCHAR(20) NOT NULL,
  `nome_razao_social` VARCHAR(255) NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `dt_nascimento` DATE NULL,
  `dt_criacao` DATE NOT NULL,
  `dt_atualizacao` DATE NULL,
  `logradouro` VARCHAR(255) NOT NULL,
  `numero` INT(11) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  `cep` INT(11) NOT NULL,
  `complemento` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`, `cpf_cnpj`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`cpf_cnpj` ASC))
ENGINE = InnoDB
COMMENT = 'Tabela responsável por manter dados dos usuários, pessoas físicas e jurídicas.';

-- -----------------------------------------------------
-- Table `bring2medb`.`tb_malote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bring2medb`.`tb_malote` ;

CREATE TABLE IF NOT EXISTS `bring2medb`.`tb_malote` (
  `id_malote` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo_rastreio` VARCHAR(100) NULL,
  `status` VARCHAR(50) NOT NULL,
  `dt_postagem` DATE NULL,
  `dt_prev_entrega` DATE NULL,
  `dt_entrega` DATE NULL,
  `tp_transporte` VARCHAR(45) NULL,
  `id_usr_remetente` INT(11) NOT NULL,
  `id_usr_destinatario` INT(11) NOT NULL,
  PRIMARY KEY (`id_malote`),
  INDEX `id_usr_remetente_idx` (`id_usr_remetente` ASC),
  INDEX `id_usr_destinatario_idx` (`id_usr_destinatario` ASC),
  CONSTRAINT `fk_id_usr_remetente`
    FOREIGN KEY (`id_usr_remetente`)
    REFERENCES `bring2medb`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_usr_destinatario`
    FOREIGN KEY (`id_usr_destinatario`)
    REFERENCES `bring2medb`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabela para manter os dados do malote.';

-- -----------------------------------------------------
-- Table `bring2medb`.`tb_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bring2medb`.`tb_item` ;

CREATE TABLE IF NOT EXISTS `bring2medb`.`tb_item` (
  `id_item` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `peso` DOUBLE NOT NULL,
  `id_malote` INT(11),
  PRIMARY KEY (`id_item`),
  INDEX `fk_tb_malote_idx` (`id_malote` ASC),
  CONSTRAINT `fk_tb_malote`
    FOREIGN KEY (`id_malote`)
    REFERENCES `bring2medb`.`tb_malote` (`id_malote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabela para manter dados dos produtos que serão disponibilizados para envio por malote.';

-- -----------------------------------------------------
-- Table `bring2medb`.`tb_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bring2medb`.`tb_login` ;

CREATE TABLE IF NOT EXISTS `bring2medb`.`tb_login` (
  `id_usuario` INT(11) NOT NULL,
  `nm_usuario` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  INDEX `fk_id_usuario_usr_idx` (`id_usuario` ASC),
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bring2medb`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabela para manter dados de login do usuário.';


-- -----------------------------------------------------
-- Table `bring2medb`.`tb_tramite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bring2medb`.`tb_tramite` ;

CREATE TABLE IF NOT EXISTS `bring2medb`.`tb_tramite` (
  `id_malote` INT(11) NOT NULL,
  `status` VARCHAR(200) NOT NULL,
  `des_status` VARCHAR(200) NOT NULL,
  `dt_inicio` DATE NOT NULL,
  `dt_fim` DATE NULL,
  `local` VARCHAR(100) NOT NULL,
  CONSTRAINT `fk_id_malote`
    FOREIGN KEY (`id_malote`)
    REFERENCES `bring2medb`.`tb_malote` (`id_malote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabela responsável por manter todos o histórico de tramite de cada malote.';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

2.5.2.	Comandos Insert para alimentar cada tabela com 5 registros.

#TB_ITEM
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso) VALUES ('Acabamento Interno Porta Malas Ônix', 'Protetor interno do portamalas', 1, 129.90, 1);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso) VALUES ('Filtro De Ar Do Motor Onix', 'Filtro de ar', 1, 29.90, 0.1);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso) VALUES ('Filtro Ar Condicionado Ac Onix', 'Filtro do arcondicionado', 1, 24.69, 0.1);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso) VALUES ('Alça teto Trazeiro lado esquerdo', 'Alça do teto para apoio do passageiro. Lado esquerdo.', 1, 62.21, 0.2);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso) VALUES ('Alça teto Trazeiro lado direito', 'Alça do teto para apoio do passageiro. Lado direito.', 1, 58.47, 0.2);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso) VALUES ('Kit Disco Pastilhas Fluido Freio Dot4 Onix ', 'Kit com o par de disco dianteiro, pastilhas e fluido de freio', 1, 265.23, 10);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso) VALUES ('Auto Falantes 6¨ônix ', 'Jogo de quatro altofalentes', 4, 50.00, .05);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso, id_malote) VALUES ('Manta Térmica Titanium Termotape P/ Escape 10 Metro + 4 Zip', 'Manta para isolamento de escapamentos de carros e motos', 1, 128.77, 0.5, 34356);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso, id_malote) VALUES ('Jogo De Raios 100% Inox Bace 3,5mm Par Xr 200', 'Raios inox dianteiro e trazeiro honda xr 200', 1, 169.99, 4, 34356);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso, id_malote) VALUES ('Chave Contato Kit Ignição Motor Moto Honda Xr 200', 'Tampa do tanque, ignição e cadeado do capacete', 1, 105.13, 0.5, 34356);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso, id_malote) VALUES ('Trava Manete Moto Teck Lock Anti Furto + Trava De Capacete', 'Cadeado anti furto', 1, 149.00, 0.7, 34356);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso) VALUES ('Ar Condicionado Split 12000 Btus Frio 220v Philco - Ph12000t', 'Arcondicionado', 1, 1339.00, 50);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso, id_malote) VALUES ('Coletor Admissão Honda Nx / Xr 200', 'Coletor de admissão do carburador', 1, 25.00, 0.1, 34356);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso, id_malote) VALUES ('Tampa Pinhão Nx 200 / Xr 200', 'Tampa de proteção do pinhão', 1, 65.00, 0.3, 34356);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso, id_malote) VALUES ('Suporte Placa Xr200 / Nx200 / Xlr125', 'Suporte placa', 1, 54.04, 0.2, 34356);
INSERT INTO tb_item (nome, descricao, quantidade, valor, peso, id_malote) VALUES ('Capa Protetor Corrente Xlx 250/350 / Nx150/200 / Xr200', 'Protetor de corrente', 1, 39.45, 0.1, 34356);
#TB_USUARIO
INSERT INTO tb_usuario (cpf_cnpj, nome_razao_social, telefone, dt_criacao, logradouro, numero, bairro, cidade, estado, cep, complemento) VALUES ('81078641072', 'Zuamir Gutemberg', '81936582403', CURDATE(), 'Rua 63', '270', 'Parque Capibaribe', 'São Lourenço da Mata', 'PE', '54720270', 'Casa');
INSERT INTO tb_usuario (cpf_cnpj, nome_razao_social, telefone, dt_criacao, logradouro, numero, bairro, cidade, estado, cep, complemento) VALUES ('96378026491', 'Caleb Tomás Pietro Ramos', '81921055324', CURDATE(), 'Rua Cajá', '977', 'Areias', 'Recife', 'PE', '50870670', 'Casa');
INSERT INTO tb_usuario (cpf_cnpj, nome_razao_social, telefone, dt_criacao, logradouro, numero, bairro, cidade, estado, cep, complemento) VALUES ('75017427406', 'Liz Mariah Sabrina Almada', '81999226792', CURDATE(), 'Rua São João', '732', 'Sítio dos Pintos', 'Recife', 'PE', '52171155', 'Apartamento 202');
INSERT INTO tb_usuario (cpf_cnpj, nome_razao_social, telefone, dt_criacao, logradouro, numero, bairro, cidade, estado, cep, complemento) VALUES ('95217987421', 'Jaqueline Sophia Eloá Campos', '', CURDATE(), 'Rua Delfino', '868', 'Nova Descoberta', 'Recife', 'PE', '52191211', 'Próximo ao Mercado Melhor preço');
INSERT INTO tb_usuario (cpf_cnpj, nome_razao_social, telefone, dt_criacao, logradouro, numero, bairro, cidade, estado, cep, complemento) VALUES ('88415969457', 'Rodrigo Gustavo Fernandes', '81998820615', CURDATE(), 'Rua Arnóbio Marques 310', '177', 'Boa Vista', 'Recife', 'PE', '50100901', 'Apto 1001');
INSERT INTO tb_usuario (cpf_cnpj, nome_razao_social, telefone, dt_criacao, logradouro, numero, bairro, cidade, estado, cep, complemento) VALUES ('66544851493', 'Lucas Oliver Kevin Ribeiro', '81988508156', CURDATE(), 'Rua Areia Branca', '676', 'Várzea', 'Recife', 'PE', '50970270', 'Casa rosada');
INSERT INTO tb_usuario (cpf_cnpj, nome_razao_social, telefone, dt_criacao, logradouro, numero, bairro, cidade, estado, cep, complemento) VALUES ('21672587476', 'Flávia Agatha Melo', '81997348848', CURDATE(), 'Rua Patriarca São José', '956', 'Jardim São Paulo', 'Recife', 'PE', '50790590', 'Casa');
INSERT INTO tb_usuario (cpf_cnpj, nome_razao_social, telefone, dt_criacao, logradouro, numero, bairro, cidade, estado, cep, complemento) VALUES ('52535914433', 'Gabriela Stefany Alves', '81993443047', CURDATE(), 'Rua Arcelina', '529', 'Tejipió', 'Recife', 'PE', '50920750', 'Casa');
INSERT INTO tb_usuario (cpf_cnpj, nome_razao_social, telefone, dt_criacao, logradouro, numero, bairro, cidade, estado, cep, complemento) VALUES ('56804010000134', 'Vieira Bolsas', '81993443047', CAST('2019,3,1 10,59,00' AS DATE), 'Rua Arcelina', '529', 'Tejipió', 'Recife', 'PE', '50920750', 'Casa');
INSERT INTO tb_usuario (cpf_cnpj, nome_razao_social, telefone, dt_criacao, logradouro, numero, bairro, cidade, estado, cep, complemento) VALUES ('70680577000177', 'Auto Car peças e acessórios', '81993443047', CAST('2019,3,20 15,59,00' AS DATE), 'Rua Arcelina', '529', 'Tejipió', 'Recife', 'PE', '50920750', 'Casa');
INSERT INTO tb_usuario (cpf_cnpj, nome_razao_social, telefone, dt_criacao, logradouro, numero, bairro, cidade, estado, cep, complemento) VALUES ('57517230000140', 'Moto Brasil', '81993443047', CAST('2019,3,31 23,59,00' AS DATE), 'Rua Arcelina', '529', 'Tejipió', 'Recife', 'PE', '50920750', 'Casa');
#TB_LOGIN
INSERT INTO tb_login (id_usuario, nm_usuario, email, senha) VALUES ('1', 'zuamirgutemberg', 'zuamirgutemberg@gmail.com', '123456');
INSERT INTO tb_login (id_usuario, nm_usuario, email, senha) VALUES ('2', 'calebtpr', 'calebtpr@gmail.com', '123456');
INSERT INTO tb_login (id_usuario, nm_usuario, email, senha) VALUES ('3', 'mariah.sabrina', 'mariah1990@outlook.com', '123456');
INSERT INTO tb_login (id_usuario, nm_usuario, email, senha) VALUES ('4', 'campossophia33', 'campossophia33@hotmail.com', '123456');
INSERT INTO tb_login (id_usuario, nm_usuario, email, senha) VALUES ('5', 'rodrigogfernandes', 'rfernandes@gmail.com', '123456');
INSERT INTO tb_login (id_usuario, nm_usuario, email, senha) VALUES ('6', 'oliverlkr', 'lkr@hotmail.com', '123456');
INSERT INTO tb_login (id_usuario, nm_usuario, email, senha) VALUES ('7', 'agathamelo123', 'agathamelo123@yahool.com.br', '123456');
INSERT INTO tb_login (id_usuario, nm_usuario, email, senha) VALUES ('8', 'gbrielaalvez', 'gbrielaalvez@uol.com.br', '123456');
INSERT INTO tb_login (id_usuario, nm_usuario, email, senha) VALUES ('9', 'vieirabolsascomercial', 'vieira.bolsas.comercial@gmail.com', '123456');
INSERT INTO tb_login (id_usuario, nm_usuario, email, senha) VALUES ('10', 'autocaroficial', 'autocar_oficial@hotmail.com', '123456');
INSERT INTO tb_login (id_usuario, nm_usuario, email, senha) VALUES ('11', 'motobrasilpecas', 'motobrasilpecas@gmail.com', '123456');
#TB_MALOTE
INSERT INTO tb_malote (id_malote, status, codigo_rastreio, tp_transporte, id_usr_remetente, id_usr_destinatario) VALUES (34356, 'ENTREGUE', 'PW189603444BR', 'CORREIOS', 11, 1);
INSERT INTO tb_malote (status, codigo_rastreio, tp_transporte, id_usr_remetente, id_usr_destinatario) VALUES ('ENVIADO', 'PW179603445BR', 'CORREIOS', 10, 1);
INSERT INTO tb_malote (status, codigo_rastreio, tp_transporte, id_usr_remetente, id_usr_destinatario) VALUES ('ENVIADO', 'PW169603446BR', 'CORREIOS', 10, 1);
INSERT INTO tb_malote (status, id_usr_remetente, id_usr_destinatario) VALUES ('CRIADO', 11, 2);
INSERT INTO tb_malote (status, id_usr_remetente, id_usr_destinatario) VALUES ('CRIADO', 11, 4);
INSERT INTO tb_malote (status, id_usr_remetente, id_usr_destinatario) VALUES ('CRIADO', 11, 7);
INSERT INTO tb_malote (status, id_usr_remetente, id_usr_destinatario) VALUES ('CRIADO', 11, 6);
INSERT INTO tb_malote (status, id_usr_remetente, id_usr_destinatario) VALUES ('CRIADO', 11, 8);
#TB_TRAMITE
INSERT INTO tb_tramite (id_malote, status, des_status, dt_inicio, dt_fim, local) VALUES (34356, 'Objeto postado após o horário limite da unidade', 'Sujeito a encaminhamento no próximo dia útil', CAST('2020,2,10 18,24,00' AS DATE), CAST('2020,2,10 18,27,00' AS DATE), 'Fortaleza / CE');
INSERT INTO tb_tramite (id_malote, status, des_status, dt_inicio, dt_fim, local) VALUES (34356, 'Objeto encaminhado', 'de Agência dos Correios em Fortaleza / CE para Unidade de Tratamento em RECIFE / PE', CAST('2020,2,10 18,27,00' AS DATE), CAST('2020,2,18 14,39,00' AS DATE), 'Fortaleza / CE');
INSERT INTO tb_tramite (id_malote, status, des_status, dt_inicio, dt_fim, local) VALUES (34356, 'Objeto encaminhado', 'de Unidade de Tratamento em SALVADOR / BA para Unidade de Tratamento em RECIFE / PE', CAST('2020,2,18 14,39,00' AS DATE), CAST('2020,2,20 13,12,00' AS DATE), 'SALVADOR / BA');
INSERT INTO tb_tramite (id_malote, status, des_status, dt_inicio, dt_fim, local) VALUES (34356, 'Objeto encaminhado', 'de Unidade de Tratamento em RECIFE / PE para Unidade de Distribuição em RECIFE / PE', CAST('2020,2,20 13,12,00' AS DATE), CAST('2020,2,21 08,04,00' AS DATE), 'RECIFE / PE');
INSERT INTO tb_tramite (id_malote, status, des_status, dt_inicio, dt_fim, local) VALUES (34356, 'Objeto saiu para entrega ao destinatário', '', CAST('2020,2,21 08,04,00' AS DATE), CAST('2020,2,21 14,09,00' AS DATE), 'RECIFE / PE');
INSERT INTO tb_tramite (id_malote, status, des_status, dt_inicio, local) VALUES (34356, 'Objeto entregue ao destinatário', '', CAST('2020,2,21 14,09,00' AS DATE), 'RECIFE / PE');
