-- MySQL Script generated by MySQL Workbench
-- qui 23 abr 2020 20:13:07 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bring2medb
-- -----------------------------------------------------
-- Banco de dados da Aplicação Bring2Me.
DROP SCHEMA IF EXISTS `bring2medb` ;

-- -----------------------------------------------------
-- Schema bring2medb
--
-- Banco de dados da Aplicação Bring2Me.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bring2medb` DEFAULT CHARACTER SET utf8 ;
USE `bring2medb` ;

-- -----------------------------------------------------
-- Table `bring2medb`.`tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bring2medb`.`tb_usuario` ;

CREATE TABLE IF NOT EXISTS `bring2medb`.`tb_usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf_cnpj` VARCHAR(20) NOT NULL,
  `nome_razao_social` VARCHAR(255) NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NULL,
  `dt_criacao` DATE NOT NULL,
  `dt_atualizacao` DATE NULL,
  `logradouro` VARCHAR(255) NOT NULL,
  `numero` INT(11) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  `cep` INT(11) NOT NULL,
  `complemento` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`, `cpf_cnpj`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`cpf_cnpj` ASC))
ENGINE = InnoDB
COMMENT = 'Tabela responsável por manter dados dos usuários, pessoas físicas e jurídicas.';

-- -----------------------------------------------------
-- Table `bring2medb`.`tb_malote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bring2medb`.`tb_malote` ;

CREATE TABLE IF NOT EXISTS `bring2medb`.`tb_malote` (
  `id_malote` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo_rastreio` VARCHAR(100) NULL,
  `status` VARCHAR(50) NOT NULL,
  `dt_postagem` DATE NULL,
  `dt_prev_entrega` DATE NULL,
  `dt_entrega` DATE NULL,
  `tp_transporte` VARCHAR(45) NULL,
  `id_usr_remetente` INT(11) NOT NULL,
  `id_usr_destinatario` INT(11) NOT NULL,
  PRIMARY KEY (`id_malote`),
  INDEX `id_usr_remetente_idx` (`id_usr_remetente` ASC),
  INDEX `id_usr_destinatario_idx` (`id_usr_destinatario` ASC),
  CONSTRAINT `fk_id_usr_remetente`
    FOREIGN KEY (`id_usr_remetente`)
    REFERENCES `bring2medb`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_usr_destinatario`
    FOREIGN KEY (`id_usr_destinatario`)
    REFERENCES `bring2medb`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabela para manter os dados do malote.';

-- -----------------------------------------------------
-- Table `bring2medb`.`tb_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bring2medb`.`tb_item` ;

CREATE TABLE IF NOT EXISTS `bring2medb`.`tb_item` (
  `id_item` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `peso` DOUBLE NOT NULL,
  `id_malote` INT(11),
  PRIMARY KEY (`id_item`),
  INDEX `fk_tb_malote_idx` (`id_malote` ASC),
  CONSTRAINT `fk_tb_malote`
    FOREIGN KEY (`id_malote`)
    REFERENCES `bring2medb`.`tb_malote` (`id_malote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabela para manter dados dos produtos que serão disponibilizados para envio por malote.';

-- -----------------------------------------------------
-- Table `bring2medb`.`tb_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bring2medb`.`tb_login` ;

CREATE TABLE IF NOT EXISTS `bring2medb`.`tb_login` (
  `id_login` INT(11) NOT NULL,
  `nm_usuario` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_login`),
  UNIQUE INDEX `id_login` (`id_login` ASC))
ENGINE = InnoDB
COMMENT = 'Tabela para manter dados de login do usuário.';

-- -----------------------------------------------------
-- Table `bring2medb`.`tb_tramite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bring2medb`.`tb_tramite` ;

CREATE TABLE IF NOT EXISTS `bring2medb`.`tb_tramite` (
  `id_malote` INT(11) NOT NULL,
  `status` VARCHAR(200) NOT NULL,
  `des_status` VARCHAR(200) NOT NULL,
  `dt_inicio` DATE NOT NULL,
  `dt_fim` DATE NULL,
  `local` VARCHAR(100) NOT NULL,
  CONSTRAINT `fk_id_malote`
    FOREIGN KEY (`id_malote`)
    REFERENCES `bring2medb`.`tb_malote` (`id_malote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabela responsável por manter todos o histórico de tramite de cada malote.';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;